### ISSUE TITLE
Thank You and Question About Logins

### ISSUE THREAD

**Issue by OllyHill** [djhohnstein/SharpChrome#6]
Thank you so much for updating this project to work with Chrome 80+. Everything is working well with cookies but looks like logins are not being decrypted. I tried "all" and "logins" and get the output *Done. I confirmed I have an entry in passwords under settings.

Thanks again mate.
Olly

**Comment by djhohnstein** [comment]
![image](https://user-images.githubusercontent.com/9327224/77462701-b5892080-6dc1-11ea-9c6f-e01025ee37d0.png)

Appears to work here. Would you mind taking a similar screenshot?

**Comment by OllyHill** [comment]
Strange mate. Cookies work great, but logins do not. I built the solution with the following frameworks in Visual Studio and still get problems: 4, 4.5, 4.6 and 4.6.1. 

Here's what I'm seeing:
![visualstudiooutput](https://user-images.githubusercontent.com/57673743/77502351-05eb9700-6e31-11ea-8a85-ba61c0f391a3.png)
![chromeversion](https://user-images.githubusercontent.com/57673743/77502358-0c7a0e80-6e31-11ea-977a-3d4ebf8200a3.png)
![examplepassword](https://user-images.githubusercontent.com/57673743/77502362-0edc6880-6e31-11ea-9037-6a4fad0c194d.png)
![commandprompt](https://user-images.githubusercontent.com/57673743/77502366-113ec280-6e31-11ea-9055-99f31ce3fc14.png)

Based on the picture from Visual Studio 2019, I'm getting some errors when building the solution which may be the issue. That output says:
```
1>------ Build started: Project: SharpChrome, Configuration: Debug Any CPU ------
1>A:\Apps\SharpChrome-master_03_18_2020\SharpChrome-master\Program.cs(54,18,54,30): warning CS0219: The variable 'getBookmarks' is assigned but its value is never used
1>A:\Apps\SharpChrome-master_03_18_2020\SharpChrome-master\Program.cs(56,18,56,28): warning CS0219: The variable 'useTmpFile' is assigned but its value is never used
1>A:\Apps\SharpChrome-master_03_18_2020\SharpChrome-master\Program.cs(57,18,57,37): warning CS0219: The variable 'useBCryptDecryption' is assigned but its value is never used
1>A:\Apps\SharpChrome-master_03_18_2020\SharpChrome-master\Program.cs(350,21,350,49): warning CS0252: Possible unintended reference comparison; to get a value comparison, cast the left hand side to type 'string'
1>A:\Apps\SharpChrome-master_03_18_2020\SharpChrome-master\src\os_win_c.cs(2059,12,2059,17): warning CS0219: The variable 'dwRet' is assigned but its value is never used
1>A:\Apps\SharpChrome-master_03_18_2020\SharpChrome-master\src\os_win_c.cs(2060,11,2060,18): warning CS0219: The variable 'dwDummy' is assigned but its value is never used
1>A:\Apps\SharpChrome-master_03_18_2020\SharpChrome-master\src\os_win_c.cs(2278,16,2278,18): warning CS0219: The variable 'ft' is assigned but its value is never used
1>A:\Apps\SharpChrome-master_03_18_2020\SharpChrome-master\src\pager_c.cs(2256,7,2256,15): warning CS0162: Unreachable code detected
1>  SharpChrome -> A:\Apps\SharpChrome-master_03_18_2020\SharpChrome-master\bin\Debug\SharpChrome.exe
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
```

**Comment by djhohnstein** [comment]
Last thing:

Can you download and run Mimikatz and verify that the latest version of Mimikatz will decrypt those credentials? e.g., run the following command:

`mimikatz dpapi::chrome /in:"%localappdata%\Google\Chrome\User Data\Default\Login Data"`

If that decrypts your logins but the assembly doesn't, I'll have something to investigate more rigorously.

**Comment by OllyHill** [comment]
Thanks for the help mate. I haven't used mimikatz in quite some time and not for its DPAPI functions so hope I did it correctly. Here's the output:

![W7 (Z)-2020-03-28-07-50-54](https://user-images.githubusercontent.com/57673743/77822511-e15e1c00-70c9-11ea-85e5-01d45cfb7ce3.png)

**Comment by djhohnstein** [comment]
Looks like Mimikatz also doesn't see whatever login you have, so I'd mark this as anomalous. The last two questions I have are:

1. Is the password UTF8 or does it contain Unicode characters?
2. What's the domain? Ifyou're comfortable sharing the it with me, I can try and replicate.

**Comment by OllyHill** [comment]
Did some further testing and getting mixed results from 2 different computers. I have a Win10 machine with a single saved login  where the password is not shown, but in the old version of SharpChrome it was. I have a Win7 machine (screenshots above) that we know doesn't work. This website is instagram and yes, it has unicode characters. Interestingly on this Win7 machine, I just saved my login to Dropbox and now that shows up (but instagram still doesn't).

**Comment by djhohnstein** [comment]
I'm assuming it's this line here then that might be giving issues:

https://github.com/djhohnstein/SharpChrome/blob/master/ChromeCredentialManager.cs#L260

You could try changing ASCII to UTF-8 and seeing if it fixes the problem. I believe this is where the issue is though

**Comment by djhohnstein** [comment]
I updated the code to now support UTF8 encodings. It may or may not work for your use case, but in my tests it handled unicode properly. If it works I'll close the issue, and if not, I don't know what the issue is, and you'll need to give me the troublesome character in your password for me to troubleshoot.

**Comment by OllyHill** [comment]
Noticed the new name mate. Spot on.

The password for Dropbox works, but instagram still does not. The password is a mix of uppercase, lowercase, numbers and an exclamation mark.

I wonder if it's related to the new chrome AES algorithm because the Instagram password was saved pre-Chrome 80 and the DropBox password was saved after.

Either way mate, I appreciate the help and the project. I'll close this and re-open if I can help later.
